metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  myexp:
    envs:
    - host
    path: pipelines/myexp
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
  cloudlab-benchmarking:
    envs:
    - host
    path: pipelines/cloudlab-benchmarking
    stages:
    - setup.sh
    - run.sh
    - teardown.sh

popperized:
- github/popperized
